# Generated by Django 5.2.5 on 2025-08-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="source",
        ),
        migrations.AddField(
            model_name="route",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="routes_from",
                to="core.airport",
            ),
        ),
    ]
