# Generated by Django 5.2.5 on 2025-08-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_ticket_flight_alter_ticket_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(null=True, upload_to="airplane_image_path"),
        ),
    ]
