# Generated by Django 5.2.5 on 2025-09-02 11:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_airplane_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=core.models.airplane_image_path
            ),
        ),
    ]
